# DatabaseTool MySQL datasource configuration
# This file is used by DataSourceService (database_tool prefix)
database_use:
  datasource:
    amanus:
      type: mysql
      enable: false
      url: jdbc:mysql://39.99.135.141:3306/talent_pool?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: QWER$#@!
    # H2 配置示例
    testdb:
      type: h2
      enable: true
      url: jdbc:h2:file:./h2-data/openmanus_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
      driver-class-name: org.h2.Driver
      username: sa
      password: $FSD#@!@#!#$!12341234
